<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hoon</string>
	</array>
	<key>name</key>
	<string>hoon</string>
	<key>patterns</key>
	<array>
    <!-- colcol -->
		<dict>
			<key>begin</key>
			<string>::</string>
			<key>comment</key>
			<string>comment</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.hoon</string>
		</dict>
    <!-- block string (double quotes) -->
		<dict>
			<key>begin</key>
			<string>\s*"""</string>
			<key>comment</key>
			<string>doqbloq</string>
			<key>end</key>
			<string>\s*"""</string>
			<key>name</key>
			<string>string.quoted.double.hoon</string>
		</dict>
    <!-- block string (double quotes) -->
		<dict>
			<key>begin</key>
			<string>\s*'''</string>
			<key>comment</key>
			<string>soqbloq</string>
			<key>end</key>
			<string>\s*'''</string>
			<key>name</key>
			<string>string.quoted.double.hoon</string>
		</dict>
    <!-- tape -->
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>comment</key>
			<string>tape</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.hoon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.|[^"]</string>
				</dict>
			</array>
		</dict>
    <!-- cord -->
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>comment</key>
			<string>cord</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.hoon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.|[^']</string>
				</dict>
			</array>
		</dict>
    <!-- TODO what is this? -->
		<!-- <dict>
			<key>comment</key>
			<string>arm</string>
			<key>match</key>
			<string>[a-z]([a-z0-9-]*[a-z0-9])?/</string>
			<key>name</key>
			<string>constant.character.hoon</string>
		</dict> -->
    <!-- arm -->
		<dict>
			<key>begin</key>
			<string>\+[-+]  (?=[a-z]([a-z0-9-]*[a-z0-9])?)</string>
			<key>comment</key>
			<string>arm</string>
			<key>contentName</key>
			<string>entity.name.function.hoon</string>
			<key>end</key>
			<string>(?![a-z0-9-])</string>
		</dict>
    <!-- term -->
		<dict>
			<key>comment</key>
			<string>term</string>
			<key>match</key>
			<string>%[a-z]([a-z0-9-]*[a-z0-9])?</string>
			<key>name</key>
			<string>storage.type.hoon</string>
		</dict>
    <!-- type (@u, @uv, @uvF, etc.) -->
		<dict>
			<key>comment</key>
			<string>aura</string>
			<key>match</key>
			<string>@[a-z]([a-zA-Z0-9-]*[a-zA-Z0-9])?</string>
			<key>name</key>
			<string>storage.type.hoon</string>
		</dict>
    <!-- loobean (%.y, %.n, .y, .n) -->
    <dict>
			<key>comment</key>
			<string>loobean</string>
			<key>match</key>
			<string>(\%?\.n|\%?\.y)</string>
			<key>name</key>
			<string>constant.language.hoon</string>
		</dict>
    <!-- rune -->
		<dict>
			<key>comment</key>
			<string>rune</string>
			<key>match</key>
      <string>(\+\||\+\$|\+\+|\+\*|\|\$|\|\_|\|:|\|\%|\|\.|\|\^|\|\-|\|\~|\|\*|\|\=|\|\@|\|\?|\$\||\$\_|\$\%|\$:|\$&lt;|\$&gt;|\$\-|\$\^|\$&amp;|\$\~|\$\@|\$\=|\$\?|\%\_|\%:|\%\.|\%\-|\%\^|\%\+|\%\~|\%\*|\%\=|:\_|:\-|:\^|:\+|:\~|:\*|\.\^|\.\+|\.\*|\.\=|\.\?|\/\$|\/\%|\/\-|\/\+|\/\=|\/\*|\/\~|\/\?|\^\||\^:|\^\.|\^\-|\^\+|\^&amp;|\^\~|\^\*|\^\=|\^\?|\;:|\;\/|\;&lt;|\;\+|\;\;|\;\~|:\*|\;\=|\~\||\~\$|\~\_|\~\%|\~\/|\~&lt;|\~&gt;|\~\+|\~&amp;|\~&amp;|\~\=|\~\?|\~\!|\=\||\=:|\=\,|\=\.|\=\/|\=&lt;|\=&gt;|\=\-|\=\^|\=\+|\=\;|\=\~|\=\*|\=\?|\?\||\?:|\?\.|\?&lt;|\?&gt;|\?\-|\?\^|\?\+|\?&amp;|\?\@|\?\~|\?\=|\?\!|\=\=|\-\-|\!:|\!\,|\!\.|\!&lt;|\!&gt;|\!\;|\!\@|\!\=|\!\?|\!\!)</string>
			<key>name</key>
			<string>keyword.control.hoon</string>
		</dict>
    <!-- constant loobean (%&, %|) -->
    <dict>
			<key>comment</key>
			<string>loobean</string>
			<key>match</key>
			<string>(\%\||%&amp;)</string>
			<key>name</key>
			<string>constant.language.hoon</string>
		</dict>
    <!-- literal loobean (&, |) -->
    <dict>
			<key>comment</key>
			<string>loobean</string>
			<key>match</key>
			<string>(\||&amp;)</string>
			<key>name</key>
			<string>constant.language.hoon</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.hoon</string>
	<key>uuid</key>
	<string>9a56507d-ae34-4bd0-84fa-079029cb9509</string>
</dict>
</plist>
