<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>hoon</string>
	</array>
	<key>name</key>
	<string>hoon</string>
	<key>patterns</key>
	<array>
    <!-- LOOBEANS -->
      <!-- loobean (%.y, %.n, .y, .n) -->
        <dict>
          <key>comment</key>
          <string>loobean</string>
          <key>match</key>
          <string>(\%?\.n|\%?\.y)</string>
          <key>name</key>
          <string>constant.language.hoon</string>
        </dict>
        <!-- TODO exclude bar runes from this rule -->
        <!-- constant loobean (%&, %|, &, |) -->
        <!-- <dict>
          <key>comment</key>
          <string>loobean</string>
          <key>match</key>
          <string>(\%?\||\%?\&amp;)</string>
          <key>name</key>
          <string>constant.language.hoon</string>
        </dict> -->
    <!-- COMMENTS -->
      <dict>
        <key>begin</key>
        <string>\:\:</string>
        <key>comment</key>
        <string>comment</string>
        <key>end</key>
        <string>\n</string>
        <key>name</key>
        <string>comment.line.hoon</string>
      </dict>
    <!-- MISC. -->
      <!-- arm (++  foo, etc.)-->
      <dict>
        <key>comment</key>
        <string>arm</string>
        <key>match</key>
        <string>\+\+  [a-z]([a-z0-9-]*[a-z0-9])?</string>
        <key>name</key>
        <string>entity.name.function.hoon</string>
      </dict>
      <!-- gates in brackets -->
      <dict>
        <key>comment</key>
        <string>arm</string>
        <key>match</key>
        <!-- TODO: this avoids ~(tap by foo) etc. -->
        <string>(?<=(\s|\`|\/)\(+)[a-z]([a-z0-9-:^]*[a-z0-9-:^])?</string>
        <key>name</key>
        <string>entity.name.function.hoon</string>
      </dict>
      <!-- gates after cen runes -->
      <dict>
        <key>comment</key>
        <string>arm</string>
        <key>match</key>
        <string>(?<=(\%(\_|\:|\.|\-|\^|\+|\~|\*))(\s\s|\())[a-z]([a-z0-9-:]*[a-z0-9-:])?</string>
        <key>name</key>
        <string>entity.name.function.hoon</string>
      </dict>
    <!-- RUNES -->
      <!-- arms -->
      <dict>
        <key>comment</key>
        <string>arms</string>
        <key>match</key>
        <string>(\+\||\+\$|\+\+|\+\*)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- cores -->
      <dict>
        <key>comment</key>
        <string>cores</string>
        <key>match</key>
        <string>(\|\$|\|\_|\|\:|\|\%|\|\.|\|\^|\|\-|\|\~|\|\*|\|\=|\|\@|\|\?)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- structures -->
      <dict>
        <key>comment</key>
        <string>structures</string>
        <key>match</key>
        <string>(\$\+|\$\||\$\_|\$\%|\$\:|\$\&lt;|\$\&gt;|\$\-|\$\^|\$\&amp;|\$\~|\$\@|\$\=|\$\?)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- calls -->
      <dict>
        <key>comment</key>
        <string>calls</string>
        <key>match</key>
        <string>(\%\_|\%\:|\%\.|\%\-|\%\^|\%\+|\%\~|\%\*|\%\=)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- cells -->
      <dict>
        <key>comment</key>
        <string>cells</string>
        <key>match</key>
        <string>(\:\_|\:\-|\:\^|\:\+|\:\~|\:\*)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- nock -->
      <dict>
        <key>comment</key>
        <string>nock</string>
        <key>match</key>
        <string>(\.\^|\.\+|\.\*|\.\=|\.\?)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- imports -->
      <dict>
        <key>comment</key>
        <string>imports</string>
        <key>match</key>
        <string>(\/\$|\/\%|\/\-|\/\+|\/\=|\/\*|\/\~|\/\?)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- casts -->
      <dict>
        <key>comment</key>
        <string>casts</string>
        <key>match</key>
        <string>(\^\||\^\:|\^\.|\^\-|\^\+|\^\&amp;|\^\~|\^\*|\^\=|\^\?)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- macros -->
      <dict>
        <key>comment</key>
        <string>macros</string>
        <key>match</key>
        <string>(\;\:|\;\/|\;\&lt;|\;\+|\;\;|\;\~|\:\*|\;\=)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- hints -->
      <dict>
        <key>comment</key>
        <string>hints</string>
        <key>match</key>
        <string>(\~\||\~\$|\~\_|\~\%|\~\/|\~\&lt;|\~\&gt;|\~\+|\~\&amp;|\~\&amp;|\~\=|\~\?|\~\!)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- subject -->
      <dict>
        <key>comment</key>
        <string>subject</string>
        <key>match</key>
        <string>(\=\||\=\:|\=\,|\=\.|\=\/|\=\&lt;|\=\&gt;|\=\-|\=\^|\=\+|\=\;|\=\~|\=\*|\=\?)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- conditionals -->
      <dict>
        <key>comment</key>
        <string>conditionals</string>
        <key>match</key>
        <string>(\?\||\?\:|\?\.|\?\&lt;|\?\&gt;|\?\-|\?\^|\?\+|\?\&amp;|\?\@|\?\~|\?\=|\?\!)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- terminators -->
      <dict>
        <key>comment</key>
        <string>terminators</string>
        <key>match</key>
        <string>(\=\=|\-\-)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
      <!-- wild -->
      <dict>
        <key>comment</key>
        <string>wild</string>
        <key>match</key>
        <string>(\!\:|\!\,|\!\.|\!\&lt;|\!\&gt;|\!\;|\!\@|\!\=|\!\?|\!\!)</string>
        <key>name</key>
        <string>keyword.control.hoon</string>
      </dict>
    <!-- STRINGS -->
      <!-- TODO escape characters -->
      <!-- TODO string interpolation -->
      <!-- block string (double quotes) -->
      <dict>
        <key>begin</key>
        <string>\s*"""</string>
        <key>comment</key>
        <string>doqbloq</string>
        <key>end</key>
        <string>\s*"""</string>
        <key>name</key>
        <string>string.quoted.double.hoon</string>
      </dict>
      <!-- block string (double quotes) -->
      <dict>
        <key>begin</key>
        <string>\s*'''</string>
        <key>comment</key>
        <string>soqbloq</string>
        <key>end</key>
        <string>\s*'''</string>
        <key>name</key>
        <string>string.quoted.double.hoon</string>
      </dict>
      <!-- tape -->
      <dict>
        <key>begin</key>
        <string>\"</string>
        <key>comment</key>
        <string>tape</string>
        <key>end</key>
        <string>\"</string>
        <key>name</key>
        <string>string.quoted.double.hoon</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.|[^"]</string>
          </dict>
        </array>
      </dict>
      <!-- cord -->
      <dict>
        <key>begin</key>
        <string>\'</string>
        <key>comment</key>
        <string>cord</string>
        <key>end</key>
        <string>\'</string>
        <key>name</key>
        <string>string.quoted.single.hoon</string>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\\.|[^']</string>
          </dict>
        </array>
      </dict>
    <!-- TYPES -->
      <!-- type (@u, @uv, @uvF, etc.) -->
      <dict>
        <key>comment</key>
        <string>aura</string>
        <key>match</key>
        <string>@[a-z]([a-zA-Z0-9-]*[a-zA-Z0-9])?</string>
        <key>name</key>
        <string>storage.type.hoon</string>
      </dict>
      <!-- lusbuc structure -->
      <dict>
        <key>comment</key>
        <string>structure</string>
        <key>match</key>
        <string>(?<=\+\$\s\s)[a-zA-Z0-9-]+</string>
        <key>name</key>
        <string>storage.type.hoon</string>
      </dict>
      <!-- kethep type -->
      <dict>
        <key>comment</key>
        <string>type</string>
        <key>match</key>
        <string>(?<=\^\-\s\s)[\w\(\)\[\] -~]+</string>
        <key>end</key>
        <string>(\n|\s{2})</string>
        <key>name</key>
        <string>storage.type.hoon</string>
      </dict>
      <!-- tic cast -->
      <dict>
        <key>comment</key>
        <string>type</string>
        <key>match</key>
        <string>(?<=\`)[\w\(\)\[\] -~]+(?=\`)</string>
        <key>name</key>
        <string>storage.type.hoon</string>
      </dict>
    <!-- CONSTANTS -->
      <!-- term (%foo, %bar, etc.)-->
        <dict>
          <key>comment</key>
          <string>term</string>
          <key>match</key>
          <string>%[a-z]([a-z0-9-]*[a-z0-9])?</string>
          <key>name</key>
          <string>constant.language.hoon</string>
        </dict>
        <!-- numeric constant (%1, %2, %3, etc.)-->
        <dict>
          <key>comment</key>
          <string>constant</string>
          <key>match</key>
          <string>%[0-9]</string>
          <key>name</key>
          <string>constant.numeric.hoon</string>
        </dict>
        <!-- TODO more numeric constants -->
        <!-- literal string (%'foo', etc.) -->
        <dict>
          <key>comment</key>
          <string>constant</string>
          <key>match</key>
          <string>%'[^']*'</string>
          <key>name</key>
          <string>constant.language.hoon</string>
        </dict>
        <!-- @ta knot (~.foo, etc.) -->
        <dict>
          <key>comment</key>
          <string>knot</string>
          <key>match</key>
          <string>\~\.[a-z]([a-zA-Z0-9-]*[a-zA-Z0-9])?</string>
          <key>name</key>
          <string>constant.language.hoon</string>
        </dict>
    <!-- ACCESSORS -->
        <!-- dot (e.g. p.q) -->
        <dict>
          <key>comment</key>
          <string>accesor</string>
          <key>match</key>
          <string>((?<=[a-zA-Z0-9-])\.(?=[a-zA-Z0-9-])|(?<=[a-zA-Z0-9-])\:(?=[a-zA-Z0-9-]))</string>
          <key>name</key>
          <string>punctuation.accessor.hoon</string>
        </dict>
        <!-- lark notation (e.g. -<+>-.foo) -->
        <!-- TODO this should only highlight valid lark notation -->
        <dict>
          <key>comment</key>
          <string>lark</string>
          <key>match</key>
          <string>[-+][-+<>]+?(\.|\:)</string>
          <key>name</key>
          <string>punctuation.accessor.hoon</string>
        </dict>
        <!-- numeric tree addressing (e.g. +1:(foo bar), +6:foo, etc.) -->
        <dict>
          <key>comment</key>
          <string>tree address</string>
          <key>match</key>
          <string>\+[0-9]+\:</string>
          <key>name</key>
          <string>punctuation.accessor.hoon</string>
        </dict>
      <!-- NAMES -->
        <!-- face -->
        <dict>
          <key>comment</key>
          <string>face</string>
          <key>match</key>
          <string>((?<![a-zA-Z0-9-]=)(?<==)[a-zA-Z0-9-]+|[a-zA-Z0-9-]+(?==))</string>
          <key>name</key>
          <string>variable.other.hoon</string>
        </dict>
      <!-- TYPE -->
        <!-- tis type -->
          <dict>
            <key>comment</key>
            <string>type</string>
            <key>match</key>
            <string>((?<==)[a-zA-Z0-9:\-]+|(?<=[a-zA-Z0-9:\-]=)\([^)]*\)\s{2,})</string>
            <key>end</key>
            <string>  </string>
            <key>name</key>
            <string>storage.type.hoon</string>
          </dict>
	</array>
  <!-- TODO -->
  <!--
  @ Empty aura

  @c Unicode dependent  ~-~45fed.

  @d Date
  @da Date, absolute  ~2020.12.25..7.15.0..1ef5
  @dr Date, relative  ~d71.h19.m26.s24..9d55

  @i Internet address
  @if IPv4 address  .195.198.143.90
  @is IPv6 address  .0.0.0.0.0.1c.c3c6.8f5a

  @p Phonemic base                                           ~laszod-dozser-fosrum-fanbyr
  @q Phonemic base, unscrambled (used with Urbit HD wallet)  .~laszod-dozser-dalteb-hilsyn

  @r IEEE-754 floating-point number
  @rh Floating-point number, half-precision, 16-bit        .~~3.14
  @rs Floating-point number, single-precision, 32-bit      .3.141592653589793
  @rd Floating-point number, double-precision, 64-bit      .~3.141592653589793
  @rq Floating-point number, quadruple-precision, 128-bit  .~~~3.141592653589793

  @s Integer, signed (sign bit low)
  @sb Signed binary       \-\-0b10.0000
  @sd Signed decimal      \-\-1.000
  @sv Signed base-32      \-\-0v201.4gvml.245kc
  @sw Signed base-64      \-\-0w2.04AfS.G8xqc
  @sx Signed hexadecimal  \-\-0x2004.90fd

  @u Integer, unsigned
  @ub Unsigned binary       0b10.1011
  @uc Bitcoin address       0c1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa
  @ud Unsigned decimal      8.675.309
  @ui Unsigned decimal      0i123456789
  @uv Unsigned base-32      0v88nvd
  @uw Unsigned base-64      0wx5~J
  @ux Unsigned hexadecimal  0x84.5fed
   -->
	<key>scopeName</key>
	<string>source.hoon</string>
	<key>uuid</key>
	<string>9a56507d-ae34-4bd0-84fa-079029cb9509</string>
</dict>
</plist>
